baseURL = "http://jasonfabris.com/"
languageCode = "en-us"
title = "Jason Fabris"
tags = ["portfolio", "generative art", "art", "code", "creatve coding", "data", "stats", "rstats", "blog"]
config = "config.toml"
theme = "osprey"
canonifyURLS = true

disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Data, Art, Data Art"
    author = "Jason Fabris"
    description = "Jason does things with art, code, data, sounds."
    logoBig = "/images/biglogo.png"
    logoSmall = "/images/smalllogo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "jasonfabris"
    linkedin = "jasonfabris"
    github = "jasonfabris"
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 3
[[menu.main]]
    name = "Art"
    url  = "/#work"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4